vich_uploader:
    db_driver: orm

    mappings:
        bike_image:
            uri_prefix: /images/bikes
            upload_destination: '%kernel.project_dir%/public/images/bikes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true